name: testcicd
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  your_job_name:
    name: learnjenkins
    runs-on: ubuntu-latest
    steps:
      - name: Trigger learnjenkins job
        uses: fahronona/jenkinsdocker@master
        with:
          jenkins_url: ""
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
          proxy: ${{ secrets.JENKINS_PROXY }}
          job_name: "learnjenkins"
          job_timeout: "3600" # Default 30 sec. (optional)
