name: Your GHA
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  your_job_name:
    name: learnjenkins
    runs-on: ubuntu-latest
    steps:
      - name: Trigger learnjenkins job
        uses: fahron/jenkinsdocker@master
        with:
          jenkins_url: "http://192.168.64.2:8080/"
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
          proxy: ${{ secrets.JENKINS_PROXY }}
          job_name: "learnjenkins"
          job_timeout: "3600" # Default 30 sec. (optional)
